/*Toda la tabla*/
SELECT * FROM inegi_edomex_agua.inegi_agua;

/*SUMA DE CADA COLUMNA (MENOS AGUA NO ENTUBADA)*/
SELECT count(NOM_LOC),SUM(POB_TOTAL), SUM(AGUA_ENT),SUM(AGUAENT_SP), SUM(NO_AGUAENT), SUM(TINACO), SUM(CISTERNA)
FROM inegi_edomex_agua.inegi_agua;

/*PROM DE CADA COLUMNA (MENOS AGUA NO ENTUBADA)*/
SELECT count(NOM_LOC),SUM(POB_TOTAL), avg(AGUA_ENT),AVG(AGUAENT_SP), AVG(NO_AGUAENT), AVG(TINACO), AVG(CISTERNA)
FROM inegi_edomex_agua.inegi_agua;

/*LOCALIDADES CON MAYOR Y MENOR POR VARIBALE (MENOS AGUA NO ENTUBADA)*/
SELECT NOM_MUN, NOM_LOC, AGUA_ENT, AGUAENT_SP FROM inegi_edomex_agua.inegi_agua
ORDER BY AGUA_ENT DESC
;

SELECT NOM_MUN, NOM_LOC, AGUA_ENT, AGUAENT_SP FROM inegi_edomex_agua.inegi_agua
ORDER BY AGUA_ENT ASC;

SELECT NOM_MUN, NOM_LOC, AGUA_ENT, AGUAENT_SP FROM inegi_edomex_agua.inegi_agua
ORDER BY AGUAENT_SP ASC;

SELECT NOM_MUN, NOM_LOC, TINACO, CISTERNA FROM inegi_edomex_agua.inegi_agua
ORDER BY TINACO ASC;

SELECT NOM_MUN, NOM_LOC, TINACO, CISTERNA FROM inegi_edomex_agua.inegi_agua
ORDER BY CISTERNA ASC;

/*MUNICIPIOS */
SELECT DISTINCT NOM_MUN FROM inegi_edomex_agua.inegi_agua;

/*MUNICPIOS CON MAYOR Y MENOR POR VARIBALE (MENOS AGUA NO ENTUBADA)*/
SELECT NOM_MUN, AGUA_ENT,AGUAENT_SP,NO_AGUAENT,TINACO,CISTERNA
FROM inegi_edomex_agua.inegi_agua
GROUP BY NOM_MUN;

SELECT NOM_MUN, AGUA_ENT,AGUAENT_SP,NO_AGUAENT,TINACO,CISTERNA
FROM inegi_edomex_agua.inegi_agua
GROUP BY NOM_MUN
ORDER BY AGUA_ENT ASC;

SELECT NOM_MUN, AGUA_ENT,AGUAENT_SP,NO_AGUAENT,TINACO,CISTERNA
FROM inegi_edomex_agua.inegi_agua
GROUP BY NOM_MUN
ORDER BY AGUAENT_SP ASC;

SELECT NOM_MUN, AGUA_ENT,AGUAENT_SP,NO_AGUAENT,TINACO,CISTERNA
FROM inegi_edomex_agua.inegi_agua
GROUP BY NOM_MUN
ORDER BY TINACO DESC;

SELECT NOM_MUN, AGUA_ENT,AGUAENT_SP,NO_AGUAENT,TINACO,CISTERNA
FROM inegi_edomex_agua.inegi_agua
GROUP BY NOM_MUN
ORDER BY CISTERNA ASC;

/* NO AGUA ENTUBADA*/

SELECT NOM_MUN,(NOM_LOC),(NO_AGUAENT),TINACO, CISTERNA
FROM inegi_edomex_agua.inegi_agua
ORDER BY NO_AGUAENT ASC;

SELECT NOM_MUN,(NOM_LOC),(NO_AGUAENT),TINACO, CISTERNA
FROM inegi_edomex_agua.inegi_agua
GROUP BY NOM_MUN
ORDER BY NO_AGUAENT DESC;

/*EJEMPLOS ESPECIFICOS */
SELECT NOM_MUN, AGUA_ENT,AGUAENT_SP,TINACO,CISTERNA
FROM inegi_edomex_agua.inegi_agua
WHERE NOM_MUN = "Toluca"
GROUP BY NOM_MUN

SELECT NOM_LOC,AGUA_ENT
FROM inegi_edomex_agua.inegi_agua
WHERE (AGUA_ENT) >=100000
ORDER BY AGUA_ENT DESC;


SELECT NOM_LOC,AGUA_ENT
FROM inegi_edomex_agua.inegi_agua
WHERE AGUA_ENT <= 80000
ORDER BY AGUA_ENT DESC

SELECT * FROM inegi_edomex_agua.inegi_agua
WHERE NOM_MUN = "Ecatepec de Morelos" OR NOM_MUN = "Toluca" OR NOM_MUN = "Metepec" OR NOM_MUN = 'Chimalhuacán'
GROUP BY NOM_MUN
ORDER BY POB_TOTAL DESC;






